# Generated by Django 2.2.6 on 2019-10-12 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='lawyer_id',
            new_name='lawyer',
        ),
    ]
