# Generated by Django 2.2.6 on 2019-10-12 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='descripttion',
            new_name='description',
        ),
    ]
